# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- cron: "0 2 * * *"
  displayName: "Daily nightly build"
  always: true

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Docker login    
      inputs:
        containerRegistry: 'cryxy@docker@hub'
        command: 'login'
    - task: Docker@2
      displayName: Build and push the image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: cryxy/prosody-extended
        tags: |
          $(tag)