name: Docker Image CI

on: 
  push:
    branches:
    - master
    - release/*
  schedule:
  - cron: "0 2 * * 1-7"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag prosody-extended:$(date +%s)
